#!bin/bash

sudo apt install -y vim vim-runtime vim-common #Install Vim because we can

sudo apt install -y tcpdump #So I can take a network dump

sudo cp BOREALIS_Cam/.bashrc /home/pi/.bashrc #Replace shell config

